# Generated by Django 4.2 on 2023-05-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_options_invoice_bankaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bankaccount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_credited',
        ),
    ]
