# Generated by Django 4.2 on 2023-06-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
