# Generated by Django 4.2 on 2023-06-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoice_is_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='is_credit',
            new_name='is_credited',
        ),
    ]
